# This workflow will build an Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and test
      run: xcodebuild clean test -scheme "Week Number" -project "Week Number.xcodeproj" -destination "platform=macOS"